package com.oj.linglian.dao;

import java.util.List;

import com.oj.linglian.entity.Question;

public interface IQuestionDao {
    public int update(Question question, Question keyQuestion);
    public int updateOfQuestionId(Question question, String questionId);
    public int updateOfTitle(Question question, String title);
    public int updateOfBody(Question question, String body);
    public int updateOfScore(Question question, String score);
    public int updateOfDemoCode(Question question, String demoCode);
    public int updateOfRightPeople(Question question, String rightPeople);
    public int updateOfMainPeople(Question question, String mainPeople);
    public int updateOfStartTime(Question question, String startTime);
    public int updateOfEndTime(Question question, String endTime);
    public int updateOfInputFormat(Question question, String inputFormat);
    public int updateOfOutputFormat(Question question, String outputFormat);
    public int updateOfInputTest(Question question, String inputTest);
    public int updateOfOutputTest(Question question, String outputTest);
    public int updateOfContestId(Question question, String contestId);
    public int updateOfUserId(Question question, String userId);
    public int updateOfQuestionIdAndTitle(Question question, String questionId, String title);
    public int updateOfQuestionIdAndBody(Question question, String questionId, String body);
    public int updateOfQuestionIdAndScore(Question question, String questionId, String score);
    public int updateOfQuestionIdAndDemoCode(Question question, String questionId, String demoCode);
    public int updateOfQuestionIdAndRightPeople(Question question, String questionId, String rightPeople);
    public int updateOfQuestionIdAndMainPeople(Question question, String questionId, String mainPeople);
    public int updateOfQuestionIdAndStartTime(Question question, String questionId, String startTime);
    public int updateOfQuestionIdAndEndTime(Question question, String questionId, String endTime);
    public int updateOfQuestionIdAndInputFormat(Question question, String questionId, String inputFormat);
    public int updateOfQuestionIdAndOutputFormat(Question question, String questionId, String outputFormat);
    public int updateOfQuestionIdAndInputTest(Question question, String questionId, String inputTest);
    public int updateOfQuestionIdAndOutputTest(Question question, String questionId, String outputTest);
    public int updateOfQuestionIdAndContestId(Question question, String questionId, String contestId);
    public int updateOfQuestionIdAndUserId(Question question, String questionId, String userId);
    public int updateOfTitleAndBody(Question question, String title, String body);
    public int updateOfTitleAndScore(Question question, String title, String score);
    public int updateOfTitleAndDemoCode(Question question, String title, String demoCode);
    public int updateOfTitleAndRightPeople(Question question, String title, String rightPeople);
    public int updateOfTitleAndMainPeople(Question question, String title, String mainPeople);
    public int updateOfTitleAndStartTime(Question question, String title, String startTime);
    public int updateOfTitleAndEndTime(Question question, String title, String endTime);
    public int updateOfTitleAndInputFormat(Question question, String title, String inputFormat);
    public int updateOfTitleAndOutputFormat(Question question, String title, String outputFormat);
    public int updateOfTitleAndInputTest(Question question, String title, String inputTest);
    public int updateOfTitleAndOutputTest(Question question, String title, String outputTest);
    public int updateOfTitleAndContestId(Question question, String title, String contestId);
    public int updateOfTitleAndUserId(Question question, String title, String userId);
    public int updateOfBodyAndScore(Question question, String body, String score);
    public int updateOfBodyAndDemoCode(Question question, String body, String demoCode);
    public int updateOfBodyAndRightPeople(Question question, String body, String rightPeople);
    public int updateOfBodyAndMainPeople(Question question, String body, String mainPeople);
    public int updateOfBodyAndStartTime(Question question, String body, String startTime);
    public int updateOfBodyAndEndTime(Question question, String body, String endTime);
    public int updateOfBodyAndInputFormat(Question question, String body, String inputFormat);
    public int updateOfBodyAndOutputFormat(Question question, String body, String outputFormat);
    public int updateOfBodyAndInputTest(Question question, String body, String inputTest);
    public int updateOfBodyAndOutputTest(Question question, String body, String outputTest);
    public int updateOfBodyAndContestId(Question question, String body, String contestId);
    public int updateOfBodyAndUserId(Question question, String body, String userId);
    public int updateOfScoreAndDemoCode(Question question, String score, String demoCode);
    public int updateOfScoreAndRightPeople(Question question, String score, String rightPeople);
    public int updateOfScoreAndMainPeople(Question question, String score, String mainPeople);
    public int updateOfScoreAndStartTime(Question question, String score, String startTime);
    public int updateOfScoreAndEndTime(Question question, String score, String endTime);
    public int updateOfScoreAndInputFormat(Question question, String score, String inputFormat);
    public int updateOfScoreAndOutputFormat(Question question, String score, String outputFormat);
    public int updateOfScoreAndInputTest(Question question, String score, String inputTest);
    public int updateOfScoreAndOutputTest(Question question, String score, String outputTest);
    public int updateOfScoreAndContestId(Question question, String score, String contestId);
    public int updateOfScoreAndUserId(Question question, String score, String userId);
    public int updateOfDemoCodeAndRightPeople(Question question, String demoCode, String rightPeople);
    public int updateOfDemoCodeAndMainPeople(Question question, String demoCode, String mainPeople);
    public int updateOfDemoCodeAndStartTime(Question question, String demoCode, String startTime);
    public int updateOfDemoCodeAndEndTime(Question question, String demoCode, String endTime);
    public int updateOfDemoCodeAndInputFormat(Question question, String demoCode, String inputFormat);
    public int updateOfDemoCodeAndOutputFormat(Question question, String demoCode, String outputFormat);
    public int updateOfDemoCodeAndInputTest(Question question, String demoCode, String inputTest);
    public int updateOfDemoCodeAndOutputTest(Question question, String demoCode, String outputTest);
    public int updateOfDemoCodeAndContestId(Question question, String demoCode, String contestId);
    public int updateOfDemoCodeAndUserId(Question question, String demoCode, String userId);
    public int updateOfRightPeopleAndMainPeople(Question question, String rightPeople, String mainPeople);
    public int updateOfRightPeopleAndStartTime(Question question, String rightPeople, String startTime);
    public int updateOfRightPeopleAndEndTime(Question question, String rightPeople, String endTime);
    public int updateOfRightPeopleAndInputFormat(Question question, String rightPeople, String inputFormat);
    public int updateOfRightPeopleAndOutputFormat(Question question, String rightPeople, String outputFormat);
    public int updateOfRightPeopleAndInputTest(Question question, String rightPeople, String inputTest);
    public int updateOfRightPeopleAndOutputTest(Question question, String rightPeople, String outputTest);
    public int updateOfRightPeopleAndContestId(Question question, String rightPeople, String contestId);
    public int updateOfRightPeopleAndUserId(Question question, String rightPeople, String userId);
    public int updateOfMainPeopleAndStartTime(Question question, String mainPeople, String startTime);
    public int updateOfMainPeopleAndEndTime(Question question, String mainPeople, String endTime);
    public int updateOfMainPeopleAndInputFormat(Question question, String mainPeople, String inputFormat);
    public int updateOfMainPeopleAndOutputFormat(Question question, String mainPeople, String outputFormat);
    public int updateOfMainPeopleAndInputTest(Question question, String mainPeople, String inputTest);
    public int updateOfMainPeopleAndOutputTest(Question question, String mainPeople, String outputTest);
    public int updateOfMainPeopleAndContestId(Question question, String mainPeople, String contestId);
    public int updateOfMainPeopleAndUserId(Question question, String mainPeople, String userId);
    public int updateOfStartTimeAndEndTime(Question question, String startTime, String endTime);
    public int updateOfStartTimeAndInputFormat(Question question, String startTime, String inputFormat);
    public int updateOfStartTimeAndOutputFormat(Question question, String startTime, String outputFormat);
    public int updateOfStartTimeAndInputTest(Question question, String startTime, String inputTest);
    public int updateOfStartTimeAndOutputTest(Question question, String startTime, String outputTest);
    public int updateOfStartTimeAndContestId(Question question, String startTime, String contestId);
    public int updateOfStartTimeAndUserId(Question question, String startTime, String userId);
    public int updateOfEndTimeAndInputFormat(Question question, String endTime, String inputFormat);
    public int updateOfEndTimeAndOutputFormat(Question question, String endTime, String outputFormat);
    public int updateOfEndTimeAndInputTest(Question question, String endTime, String inputTest);
    public int updateOfEndTimeAndOutputTest(Question question, String endTime, String outputTest);
    public int updateOfEndTimeAndContestId(Question question, String endTime, String contestId);
    public int updateOfEndTimeAndUserId(Question question, String endTime, String userId);
    public int updateOfInputFormatAndOutputFormat(Question question, String inputFormat, String outputFormat);
    public int updateOfInputFormatAndInputTest(Question question, String inputFormat, String inputTest);
    public int updateOfInputFormatAndOutputTest(Question question, String inputFormat, String outputTest);
    public int updateOfInputFormatAndContestId(Question question, String inputFormat, String contestId);
    public int updateOfInputFormatAndUserId(Question question, String inputFormat, String userId);
    public int updateOfOutputFormatAndInputTest(Question question, String outputFormat, String inputTest);
    public int updateOfOutputFormatAndOutputTest(Question question, String outputFormat, String outputTest);
    public int updateOfOutputFormatAndContestId(Question question, String outputFormat, String contestId);
    public int updateOfOutputFormatAndUserId(Question question, String outputFormat, String userId);
    public int updateOfInputTestAndOutputTest(Question question, String inputTest, String outputTest);
    public int updateOfInputTestAndContestId(Question question, String inputTest, String contestId);
    public int updateOfInputTestAndUserId(Question question, String inputTest, String userId);
    public int updateOfOutputTestAndContestId(Question question, String outputTest, String contestId);
    public int updateOfOutputTestAndUserId(Question question, String outputTest, String userId);
    public int updateOfContestIdAndUserId(Question question, String contestId, String userId);
    public int remove(Question question);
    public int removeOfQuestionId(String questionId);
    public int removeOfTitle(String title);
    public int removeOfBody(String body);
    public int removeOfScore(String score);
    public int removeOfDemoCode(String demoCode);
    public int removeOfRightPeople(String rightPeople);
    public int removeOfMainPeople(String mainPeople);
    public int removeOfStartTime(String startTime);
    public int removeOfEndTime(String endTime);
    public int removeOfInputFormat(String inputFormat);
    public int removeOfOutputFormat(String outputFormat);
    public int removeOfInputTest(String inputTest);
    public int removeOfOutputTest(String outputTest);
    public int removeOfContestId(String contestId);
    public int removeOfUserId(String userId);
    public int removeOfQuestionIdAndTitle(String questionId, String title);
    public int removeOfQuestionIdAndBody(String questionId, String body);
    public int removeOfQuestionIdAndScore(String questionId, String score);
    public int removeOfQuestionIdAndDemoCode(String questionId, String demoCode);
    public int removeOfQuestionIdAndRightPeople(String questionId, String rightPeople);
    public int removeOfQuestionIdAndMainPeople(String questionId, String mainPeople);
    public int removeOfQuestionIdAndStartTime(String questionId, String startTime);
    public int removeOfQuestionIdAndEndTime(String questionId, String endTime);
    public int removeOfQuestionIdAndInputFormat(String questionId, String inputFormat);
    public int removeOfQuestionIdAndOutputFormat(String questionId, String outputFormat);
    public int removeOfQuestionIdAndInputTest(String questionId, String inputTest);
    public int removeOfQuestionIdAndOutputTest(String questionId, String outputTest);
    public int removeOfQuestionIdAndContestId(String questionId, String contestId);
    public int removeOfQuestionIdAndUserId(String questionId, String userId);
    public int removeOfTitleAndBody(String title, String body);
    public int removeOfTitleAndScore(String title, String score);
    public int removeOfTitleAndDemoCode(String title, String demoCode);
    public int removeOfTitleAndRightPeople(String title, String rightPeople);
    public int removeOfTitleAndMainPeople(String title, String mainPeople);
    public int removeOfTitleAndStartTime(String title, String startTime);
    public int removeOfTitleAndEndTime(String title, String endTime);
    public int removeOfTitleAndInputFormat(String title, String inputFormat);
    public int removeOfTitleAndOutputFormat(String title, String outputFormat);
    public int removeOfTitleAndInputTest(String title, String inputTest);
    public int removeOfTitleAndOutputTest(String title, String outputTest);
    public int removeOfTitleAndContestId(String title, String contestId);
    public int removeOfTitleAndUserId(String title, String userId);
    public int removeOfBodyAndScore(String body, String score);
    public int removeOfBodyAndDemoCode(String body, String demoCode);
    public int removeOfBodyAndRightPeople(String body, String rightPeople);
    public int removeOfBodyAndMainPeople(String body, String mainPeople);
    public int removeOfBodyAndStartTime(String body, String startTime);
    public int removeOfBodyAndEndTime(String body, String endTime);
    public int removeOfBodyAndInputFormat(String body, String inputFormat);
    public int removeOfBodyAndOutputFormat(String body, String outputFormat);
    public int removeOfBodyAndInputTest(String body, String inputTest);
    public int removeOfBodyAndOutputTest(String body, String outputTest);
    public int removeOfBodyAndContestId(String body, String contestId);
    public int removeOfBodyAndUserId(String body, String userId);
    public int removeOfScoreAndDemoCode(String score, String demoCode);
    public int removeOfScoreAndRightPeople(String score, String rightPeople);
    public int removeOfScoreAndMainPeople(String score, String mainPeople);
    public int removeOfScoreAndStartTime(String score, String startTime);
    public int removeOfScoreAndEndTime(String score, String endTime);
    public int removeOfScoreAndInputFormat(String score, String inputFormat);
    public int removeOfScoreAndOutputFormat(String score, String outputFormat);
    public int removeOfScoreAndInputTest(String score, String inputTest);
    public int removeOfScoreAndOutputTest(String score, String outputTest);
    public int removeOfScoreAndContestId(String score, String contestId);
    public int removeOfScoreAndUserId(String score, String userId);
    public int removeOfDemoCodeAndRightPeople(String demoCode, String rightPeople);
    public int removeOfDemoCodeAndMainPeople(String demoCode, String mainPeople);
    public int removeOfDemoCodeAndStartTime(String demoCode, String startTime);
    public int removeOfDemoCodeAndEndTime(String demoCode, String endTime);
    public int removeOfDemoCodeAndInputFormat(String demoCode, String inputFormat);
    public int removeOfDemoCodeAndOutputFormat(String demoCode, String outputFormat);
    public int removeOfDemoCodeAndInputTest(String demoCode, String inputTest);
    public int removeOfDemoCodeAndOutputTest(String demoCode, String outputTest);
    public int removeOfDemoCodeAndContestId(String demoCode, String contestId);
    public int removeOfDemoCodeAndUserId(String demoCode, String userId);
    public int removeOfRightPeopleAndMainPeople(String rightPeople, String mainPeople);
    public int removeOfRightPeopleAndStartTime(String rightPeople, String startTime);
    public int removeOfRightPeopleAndEndTime(String rightPeople, String endTime);
    public int removeOfRightPeopleAndInputFormat(String rightPeople, String inputFormat);
    public int removeOfRightPeopleAndOutputFormat(String rightPeople, String outputFormat);
    public int removeOfRightPeopleAndInputTest(String rightPeople, String inputTest);
    public int removeOfRightPeopleAndOutputTest(String rightPeople, String outputTest);
    public int removeOfRightPeopleAndContestId(String rightPeople, String contestId);
    public int removeOfRightPeopleAndUserId(String rightPeople, String userId);
    public int removeOfMainPeopleAndStartTime(String mainPeople, String startTime);
    public int removeOfMainPeopleAndEndTime(String mainPeople, String endTime);
    public int removeOfMainPeopleAndInputFormat(String mainPeople, String inputFormat);
    public int removeOfMainPeopleAndOutputFormat(String mainPeople, String outputFormat);
    public int removeOfMainPeopleAndInputTest(String mainPeople, String inputTest);
    public int removeOfMainPeopleAndOutputTest(String mainPeople, String outputTest);
    public int removeOfMainPeopleAndContestId(String mainPeople, String contestId);
    public int removeOfMainPeopleAndUserId(String mainPeople, String userId);
    public int removeOfStartTimeAndEndTime(String startTime, String endTime);
    public int removeOfStartTimeAndInputFormat(String startTime, String inputFormat);
    public int removeOfStartTimeAndOutputFormat(String startTime, String outputFormat);
    public int removeOfStartTimeAndInputTest(String startTime, String inputTest);
    public int removeOfStartTimeAndOutputTest(String startTime, String outputTest);
    public int removeOfStartTimeAndContestId(String startTime, String contestId);
    public int removeOfStartTimeAndUserId(String startTime, String userId);
    public int removeOfEndTimeAndInputFormat(String endTime, String inputFormat);
    public int removeOfEndTimeAndOutputFormat(String endTime, String outputFormat);
    public int removeOfEndTimeAndInputTest(String endTime, String inputTest);
    public int removeOfEndTimeAndOutputTest(String endTime, String outputTest);
    public int removeOfEndTimeAndContestId(String endTime, String contestId);
    public int removeOfEndTimeAndUserId(String endTime, String userId);
    public int removeOfInputFormatAndOutputFormat(String inputFormat, String outputFormat);
    public int removeOfInputFormatAndInputTest(String inputFormat, String inputTest);
    public int removeOfInputFormatAndOutputTest(String inputFormat, String outputTest);
    public int removeOfInputFormatAndContestId(String inputFormat, String contestId);
    public int removeOfInputFormatAndUserId(String inputFormat, String userId);
    public int removeOfOutputFormatAndInputTest(String outputFormat, String inputTest);
    public int removeOfOutputFormatAndOutputTest(String outputFormat, String outputTest);
    public int removeOfOutputFormatAndContestId(String outputFormat, String contestId);
    public int removeOfOutputFormatAndUserId(String outputFormat, String userId);
    public int removeOfInputTestAndOutputTest(String inputTest, String outputTest);
    public int removeOfInputTestAndContestId(String inputTest, String contestId);
    public int removeOfInputTestAndUserId(String inputTest, String userId);
    public int removeOfOutputTestAndContestId(String outputTest, String contestId);
    public int removeOfOutputTestAndUserId(String outputTest, String userId);
    public int removeOfContestIdAndUserId(String contestId, String userId);
    public int insert(Question question);
    public int insertOfQuestionId(String questionId);
    public int insertOfTitle(String title);
    public int insertOfBody(String body);
    public int insertOfScore(String score);
    public int insertOfDemoCode(String demoCode);
    public int insertOfRightPeople(String rightPeople);
    public int insertOfMainPeople(String mainPeople);
    public int insertOfStartTime(String startTime);
    public int insertOfEndTime(String endTime);
    public int insertOfInputFormat(String inputFormat);
    public int insertOfOutputFormat(String outputFormat);
    public int insertOfInputTest(String inputTest);
    public int insertOfOutputTest(String outputTest);
    public int insertOfContestId(String contestId);
    public int insertOfUserId(String userId);
    public int insertOfQuestionIdAndTitle(String questionId, String title);
    public int insertOfQuestionIdAndBody(String questionId, String body);
    public int insertOfQuestionIdAndScore(String questionId, String score);
    public int insertOfQuestionIdAndDemoCode(String questionId, String demoCode);
    public int insertOfQuestionIdAndRightPeople(String questionId, String rightPeople);
    public int insertOfQuestionIdAndMainPeople(String questionId, String mainPeople);
    public int insertOfQuestionIdAndStartTime(String questionId, String startTime);
    public int insertOfQuestionIdAndEndTime(String questionId, String endTime);
    public int insertOfQuestionIdAndInputFormat(String questionId, String inputFormat);
    public int insertOfQuestionIdAndOutputFormat(String questionId, String outputFormat);
    public int insertOfQuestionIdAndInputTest(String questionId, String inputTest);
    public int insertOfQuestionIdAndOutputTest(String questionId, String outputTest);
    public int insertOfQuestionIdAndContestId(String questionId, String contestId);
    public int insertOfQuestionIdAndUserId(String questionId, String userId);
    public int insertOfTitleAndBody(String title, String body);
    public int insertOfTitleAndScore(String title, String score);
    public int insertOfTitleAndDemoCode(String title, String demoCode);
    public int insertOfTitleAndRightPeople(String title, String rightPeople);
    public int insertOfTitleAndMainPeople(String title, String mainPeople);
    public int insertOfTitleAndStartTime(String title, String startTime);
    public int insertOfTitleAndEndTime(String title, String endTime);
    public int insertOfTitleAndInputFormat(String title, String inputFormat);
    public int insertOfTitleAndOutputFormat(String title, String outputFormat);
    public int insertOfTitleAndInputTest(String title, String inputTest);
    public int insertOfTitleAndOutputTest(String title, String outputTest);
    public int insertOfTitleAndContestId(String title, String contestId);
    public int insertOfTitleAndUserId(String title, String userId);
    public int insertOfBodyAndScore(String body, String score);
    public int insertOfBodyAndDemoCode(String body, String demoCode);
    public int insertOfBodyAndRightPeople(String body, String rightPeople);
    public int insertOfBodyAndMainPeople(String body, String mainPeople);
    public int insertOfBodyAndStartTime(String body, String startTime);
    public int insertOfBodyAndEndTime(String body, String endTime);
    public int insertOfBodyAndInputFormat(String body, String inputFormat);
    public int insertOfBodyAndOutputFormat(String body, String outputFormat);
    public int insertOfBodyAndInputTest(String body, String inputTest);
    public int insertOfBodyAndOutputTest(String body, String outputTest);
    public int insertOfBodyAndContestId(String body, String contestId);
    public int insertOfBodyAndUserId(String body, String userId);
    public int insertOfScoreAndDemoCode(String score, String demoCode);
    public int insertOfScoreAndRightPeople(String score, String rightPeople);
    public int insertOfScoreAndMainPeople(String score, String mainPeople);
    public int insertOfScoreAndStartTime(String score, String startTime);
    public int insertOfScoreAndEndTime(String score, String endTime);
    public int insertOfScoreAndInputFormat(String score, String inputFormat);
    public int insertOfScoreAndOutputFormat(String score, String outputFormat);
    public int insertOfScoreAndInputTest(String score, String inputTest);
    public int insertOfScoreAndOutputTest(String score, String outputTest);
    public int insertOfScoreAndContestId(String score, String contestId);
    public int insertOfScoreAndUserId(String score, String userId);
    public int insertOfDemoCodeAndRightPeople(String demoCode, String rightPeople);
    public int insertOfDemoCodeAndMainPeople(String demoCode, String mainPeople);
    public int insertOfDemoCodeAndStartTime(String demoCode, String startTime);
    public int insertOfDemoCodeAndEndTime(String demoCode, String endTime);
    public int insertOfDemoCodeAndInputFormat(String demoCode, String inputFormat);
    public int insertOfDemoCodeAndOutputFormat(String demoCode, String outputFormat);
    public int insertOfDemoCodeAndInputTest(String demoCode, String inputTest);
    public int insertOfDemoCodeAndOutputTest(String demoCode, String outputTest);
    public int insertOfDemoCodeAndContestId(String demoCode, String contestId);
    public int insertOfDemoCodeAndUserId(String demoCode, String userId);
    public int insertOfRightPeopleAndMainPeople(String rightPeople, String mainPeople);
    public int insertOfRightPeopleAndStartTime(String rightPeople, String startTime);
    public int insertOfRightPeopleAndEndTime(String rightPeople, String endTime);
    public int insertOfRightPeopleAndInputFormat(String rightPeople, String inputFormat);
    public int insertOfRightPeopleAndOutputFormat(String rightPeople, String outputFormat);
    public int insertOfRightPeopleAndInputTest(String rightPeople, String inputTest);
    public int insertOfRightPeopleAndOutputTest(String rightPeople, String outputTest);
    public int insertOfRightPeopleAndContestId(String rightPeople, String contestId);
    public int insertOfRightPeopleAndUserId(String rightPeople, String userId);
    public int insertOfMainPeopleAndStartTime(String mainPeople, String startTime);
    public int insertOfMainPeopleAndEndTime(String mainPeople, String endTime);
    public int insertOfMainPeopleAndInputFormat(String mainPeople, String inputFormat);
    public int insertOfMainPeopleAndOutputFormat(String mainPeople, String outputFormat);
    public int insertOfMainPeopleAndInputTest(String mainPeople, String inputTest);
    public int insertOfMainPeopleAndOutputTest(String mainPeople, String outputTest);
    public int insertOfMainPeopleAndContestId(String mainPeople, String contestId);
    public int insertOfMainPeopleAndUserId(String mainPeople, String userId);
    public int insertOfStartTimeAndEndTime(String startTime, String endTime);
    public int insertOfStartTimeAndInputFormat(String startTime, String inputFormat);
    public int insertOfStartTimeAndOutputFormat(String startTime, String outputFormat);
    public int insertOfStartTimeAndInputTest(String startTime, String inputTest);
    public int insertOfStartTimeAndOutputTest(String startTime, String outputTest);
    public int insertOfStartTimeAndContestId(String startTime, String contestId);
    public int insertOfStartTimeAndUserId(String startTime, String userId);
    public int insertOfEndTimeAndInputFormat(String endTime, String inputFormat);
    public int insertOfEndTimeAndOutputFormat(String endTime, String outputFormat);
    public int insertOfEndTimeAndInputTest(String endTime, String inputTest);
    public int insertOfEndTimeAndOutputTest(String endTime, String outputTest);
    public int insertOfEndTimeAndContestId(String endTime, String contestId);
    public int insertOfEndTimeAndUserId(String endTime, String userId);
    public int insertOfInputFormatAndOutputFormat(String inputFormat, String outputFormat);
    public int insertOfInputFormatAndInputTest(String inputFormat, String inputTest);
    public int insertOfInputFormatAndOutputTest(String inputFormat, String outputTest);
    public int insertOfInputFormatAndContestId(String inputFormat, String contestId);
    public int insertOfInputFormatAndUserId(String inputFormat, String userId);
    public int insertOfOutputFormatAndInputTest(String outputFormat, String inputTest);
    public int insertOfOutputFormatAndOutputTest(String outputFormat, String outputTest);
    public int insertOfOutputFormatAndContestId(String outputFormat, String contestId);
    public int insertOfOutputFormatAndUserId(String outputFormat, String userId);
    public int insertOfInputTestAndOutputTest(String inputTest, String outputTest);
    public int insertOfInputTestAndContestId(String inputTest, String contestId);
    public int insertOfInputTestAndUserId(String inputTest, String userId);
    public int insertOfOutputTestAndContestId(String outputTest, String contestId);
    public int insertOfOutputTestAndUserId(String outputTest, String userId);
    public int insertOfContestIdAndUserId(String contestId, String userId);
    public Question getQuestion(Question question);
    public Question getQuestionOfQuestionId(String questionId);
    public Question getQuestionOfTitle(String title);
    public Question getQuestionOfBody(String body);
    public Question getQuestionOfScore(String score);
    public Question getQuestionOfDemoCode(String demoCode);
    public Question getQuestionOfRightPeople(String rightPeople);
    public Question getQuestionOfMainPeople(String mainPeople);
    public Question getQuestionOfStartTime(String startTime);
    public Question getQuestionOfEndTime(String endTime);
    public Question getQuestionOfInputFormat(String inputFormat);
    public Question getQuestionOfOutputFormat(String outputFormat);
    public Question getQuestionOfInputTest(String inputTest);
    public Question getQuestionOfOutputTest(String outputTest);
    public Question getQuestionOfContestId(String contestId);
    public Question getQuestionOfUserId(String userId);
    public Question getQuestionOfQuestionIdAndTitle(String questionId, String title);
    public Question getQuestionOfQuestionIdAndBody(String questionId, String body);
    public Question getQuestionOfQuestionIdAndScore(String questionId, String score);
    public Question getQuestionOfQuestionIdAndDemoCode(String questionId, String demoCode);
    public Question getQuestionOfQuestionIdAndRightPeople(String questionId, String rightPeople);
    public Question getQuestionOfQuestionIdAndMainPeople(String questionId, String mainPeople);
    public Question getQuestionOfQuestionIdAndStartTime(String questionId, String startTime);
    public Question getQuestionOfQuestionIdAndEndTime(String questionId, String endTime);
    public Question getQuestionOfQuestionIdAndInputFormat(String questionId, String inputFormat);
    public Question getQuestionOfQuestionIdAndOutputFormat(String questionId, String outputFormat);
    public Question getQuestionOfQuestionIdAndInputTest(String questionId, String inputTest);
    public Question getQuestionOfQuestionIdAndOutputTest(String questionId, String outputTest);
    public Question getQuestionOfQuestionIdAndContestId(String questionId, String contestId);
    public Question getQuestionOfQuestionIdAndUserId(String questionId, String userId);
    public Question getQuestionOfTitleAndBody(String title, String body);
    public Question getQuestionOfTitleAndScore(String title, String score);
    public Question getQuestionOfTitleAndDemoCode(String title, String demoCode);
    public Question getQuestionOfTitleAndRightPeople(String title, String rightPeople);
    public Question getQuestionOfTitleAndMainPeople(String title, String mainPeople);
    public Question getQuestionOfTitleAndStartTime(String title, String startTime);
    public Question getQuestionOfTitleAndEndTime(String title, String endTime);
    public Question getQuestionOfTitleAndInputFormat(String title, String inputFormat);
    public Question getQuestionOfTitleAndOutputFormat(String title, String outputFormat);
    public Question getQuestionOfTitleAndInputTest(String title, String inputTest);
    public Question getQuestionOfTitleAndOutputTest(String title, String outputTest);
    public Question getQuestionOfTitleAndContestId(String title, String contestId);
    public Question getQuestionOfTitleAndUserId(String title, String userId);
    public Question getQuestionOfBodyAndScore(String body, String score);
    public Question getQuestionOfBodyAndDemoCode(String body, String demoCode);
    public Question getQuestionOfBodyAndRightPeople(String body, String rightPeople);
    public Question getQuestionOfBodyAndMainPeople(String body, String mainPeople);
    public Question getQuestionOfBodyAndStartTime(String body, String startTime);
    public Question getQuestionOfBodyAndEndTime(String body, String endTime);
    public Question getQuestionOfBodyAndInputFormat(String body, String inputFormat);
    public Question getQuestionOfBodyAndOutputFormat(String body, String outputFormat);
    public Question getQuestionOfBodyAndInputTest(String body, String inputTest);
    public Question getQuestionOfBodyAndOutputTest(String body, String outputTest);
    public Question getQuestionOfBodyAndContestId(String body, String contestId);
    public Question getQuestionOfBodyAndUserId(String body, String userId);
    public Question getQuestionOfScoreAndDemoCode(String score, String demoCode);
    public Question getQuestionOfScoreAndRightPeople(String score, String rightPeople);
    public Question getQuestionOfScoreAndMainPeople(String score, String mainPeople);
    public Question getQuestionOfScoreAndStartTime(String score, String startTime);
    public Question getQuestionOfScoreAndEndTime(String score, String endTime);
    public Question getQuestionOfScoreAndInputFormat(String score, String inputFormat);
    public Question getQuestionOfScoreAndOutputFormat(String score, String outputFormat);
    public Question getQuestionOfScoreAndInputTest(String score, String inputTest);
    public Question getQuestionOfScoreAndOutputTest(String score, String outputTest);
    public Question getQuestionOfScoreAndContestId(String score, String contestId);
    public Question getQuestionOfScoreAndUserId(String score, String userId);
    public Question getQuestionOfDemoCodeAndRightPeople(String demoCode, String rightPeople);
    public Question getQuestionOfDemoCodeAndMainPeople(String demoCode, String mainPeople);
    public Question getQuestionOfDemoCodeAndStartTime(String demoCode, String startTime);
    public Question getQuestionOfDemoCodeAndEndTime(String demoCode, String endTime);
    public Question getQuestionOfDemoCodeAndInputFormat(String demoCode, String inputFormat);
    public Question getQuestionOfDemoCodeAndOutputFormat(String demoCode, String outputFormat);
    public Question getQuestionOfDemoCodeAndInputTest(String demoCode, String inputTest);
    public Question getQuestionOfDemoCodeAndOutputTest(String demoCode, String outputTest);
    public Question getQuestionOfDemoCodeAndContestId(String demoCode, String contestId);
    public Question getQuestionOfDemoCodeAndUserId(String demoCode, String userId);
    public Question getQuestionOfRightPeopleAndMainPeople(String rightPeople, String mainPeople);
    public Question getQuestionOfRightPeopleAndStartTime(String rightPeople, String startTime);
    public Question getQuestionOfRightPeopleAndEndTime(String rightPeople, String endTime);
    public Question getQuestionOfRightPeopleAndInputFormat(String rightPeople, String inputFormat);
    public Question getQuestionOfRightPeopleAndOutputFormat(String rightPeople, String outputFormat);
    public Question getQuestionOfRightPeopleAndInputTest(String rightPeople, String inputTest);
    public Question getQuestionOfRightPeopleAndOutputTest(String rightPeople, String outputTest);
    public Question getQuestionOfRightPeopleAndContestId(String rightPeople, String contestId);
    public Question getQuestionOfRightPeopleAndUserId(String rightPeople, String userId);
    public Question getQuestionOfMainPeopleAndStartTime(String mainPeople, String startTime);
    public Question getQuestionOfMainPeopleAndEndTime(String mainPeople, String endTime);
    public Question getQuestionOfMainPeopleAndInputFormat(String mainPeople, String inputFormat);
    public Question getQuestionOfMainPeopleAndOutputFormat(String mainPeople, String outputFormat);
    public Question getQuestionOfMainPeopleAndInputTest(String mainPeople, String inputTest);
    public Question getQuestionOfMainPeopleAndOutputTest(String mainPeople, String outputTest);
    public Question getQuestionOfMainPeopleAndContestId(String mainPeople, String contestId);
    public Question getQuestionOfMainPeopleAndUserId(String mainPeople, String userId);
    public Question getQuestionOfStartTimeAndEndTime(String startTime, String endTime);
    public Question getQuestionOfStartTimeAndInputFormat(String startTime, String inputFormat);
    public Question getQuestionOfStartTimeAndOutputFormat(String startTime, String outputFormat);
    public Question getQuestionOfStartTimeAndInputTest(String startTime, String inputTest);
    public Question getQuestionOfStartTimeAndOutputTest(String startTime, String outputTest);
    public Question getQuestionOfStartTimeAndContestId(String startTime, String contestId);
    public Question getQuestionOfStartTimeAndUserId(String startTime, String userId);
    public Question getQuestionOfEndTimeAndInputFormat(String endTime, String inputFormat);
    public Question getQuestionOfEndTimeAndOutputFormat(String endTime, String outputFormat);
    public Question getQuestionOfEndTimeAndInputTest(String endTime, String inputTest);
    public Question getQuestionOfEndTimeAndOutputTest(String endTime, String outputTest);
    public Question getQuestionOfEndTimeAndContestId(String endTime, String contestId);
    public Question getQuestionOfEndTimeAndUserId(String endTime, String userId);
    public Question getQuestionOfInputFormatAndOutputFormat(String inputFormat, String outputFormat);
    public Question getQuestionOfInputFormatAndInputTest(String inputFormat, String inputTest);
    public Question getQuestionOfInputFormatAndOutputTest(String inputFormat, String outputTest);
    public Question getQuestionOfInputFormatAndContestId(String inputFormat, String contestId);
    public Question getQuestionOfInputFormatAndUserId(String inputFormat, String userId);
    public Question getQuestionOfOutputFormatAndInputTest(String outputFormat, String inputTest);
    public Question getQuestionOfOutputFormatAndOutputTest(String outputFormat, String outputTest);
    public Question getQuestionOfOutputFormatAndContestId(String outputFormat, String contestId);
    public Question getQuestionOfOutputFormatAndUserId(String outputFormat, String userId);
    public Question getQuestionOfInputTestAndOutputTest(String inputTest, String outputTest);
    public Question getQuestionOfInputTestAndContestId(String inputTest, String contestId);
    public Question getQuestionOfInputTestAndUserId(String inputTest, String userId);
    public Question getQuestionOfOutputTestAndContestId(String outputTest, String contestId);
    public Question getQuestionOfOutputTestAndUserId(String outputTest, String userId);
    public Question getQuestionOfContestIdAndUserId(String contestId, String userId);
    public List<Question> getQuestions(Question question);
    public List<Question> getQuestionsOfQuestionId(String questionId);
    public List<Question> getQuestionsOfTitle(String title);
    public List<Question> getQuestionsOfBody(String body);
    public List<Question> getQuestionsOfScore(String score);
    public List<Question> getQuestionsOfDemoCode(String demoCode);
    public List<Question> getQuestionsOfRightPeople(String rightPeople);
    public List<Question> getQuestionsOfMainPeople(String mainPeople);
    public List<Question> getQuestionsOfStartTime(String startTime);
    public List<Question> getQuestionsOfEndTime(String endTime);
    public List<Question> getQuestionsOfInputFormat(String inputFormat);
    public List<Question> getQuestionsOfOutputFormat(String outputFormat);
    public List<Question> getQuestionsOfInputTest(String inputTest);
    public List<Question> getQuestionsOfOutputTest(String outputTest);
    public List<Question> getQuestionsOfContestId(String contestId);
    public List<Question> getQuestionsOfUserId(String userId);
    public List<Question> getQuestionsOfQuestionIdAndTitle(String questionId, String title);
    public List<Question> getQuestionsOfQuestionIdAndBody(String questionId, String body);
    public List<Question> getQuestionsOfQuestionIdAndScore(String questionId, String score);
    public List<Question> getQuestionsOfQuestionIdAndDemoCode(String questionId, String demoCode);
    public List<Question> getQuestionsOfQuestionIdAndRightPeople(String questionId, String rightPeople);
    public List<Question> getQuestionsOfQuestionIdAndMainPeople(String questionId, String mainPeople);
    public List<Question> getQuestionsOfQuestionIdAndStartTime(String questionId, String startTime);
    public List<Question> getQuestionsOfQuestionIdAndEndTime(String questionId, String endTime);
    public List<Question> getQuestionsOfQuestionIdAndInputFormat(String questionId, String inputFormat);
    public List<Question> getQuestionsOfQuestionIdAndOutputFormat(String questionId, String outputFormat);
    public List<Question> getQuestionsOfQuestionIdAndInputTest(String questionId, String inputTest);
    public List<Question> getQuestionsOfQuestionIdAndOutputTest(String questionId, String outputTest);
    public List<Question> getQuestionsOfQuestionIdAndContestId(String questionId, String contestId);
    public List<Question> getQuestionsOfQuestionIdAndUserId(String questionId, String userId);
    public List<Question> getQuestionsOfTitleAndBody(String title, String body);
    public List<Question> getQuestionsOfTitleAndScore(String title, String score);
    public List<Question> getQuestionsOfTitleAndDemoCode(String title, String demoCode);
    public List<Question> getQuestionsOfTitleAndRightPeople(String title, String rightPeople);
    public List<Question> getQuestionsOfTitleAndMainPeople(String title, String mainPeople);
    public List<Question> getQuestionsOfTitleAndStartTime(String title, String startTime);
    public List<Question> getQuestionsOfTitleAndEndTime(String title, String endTime);
    public List<Question> getQuestionsOfTitleAndInputFormat(String title, String inputFormat);
    public List<Question> getQuestionsOfTitleAndOutputFormat(String title, String outputFormat);
    public List<Question> getQuestionsOfTitleAndInputTest(String title, String inputTest);
    public List<Question> getQuestionsOfTitleAndOutputTest(String title, String outputTest);
    public List<Question> getQuestionsOfTitleAndContestId(String title, String contestId);
    public List<Question> getQuestionsOfTitleAndUserId(String title, String userId);
    public List<Question> getQuestionsOfBodyAndScore(String body, String score);
    public List<Question> getQuestionsOfBodyAndDemoCode(String body, String demoCode);
    public List<Question> getQuestionsOfBodyAndRightPeople(String body, String rightPeople);
    public List<Question> getQuestionsOfBodyAndMainPeople(String body, String mainPeople);
    public List<Question> getQuestionsOfBodyAndStartTime(String body, String startTime);
    public List<Question> getQuestionsOfBodyAndEndTime(String body, String endTime);
    public List<Question> getQuestionsOfBodyAndInputFormat(String body, String inputFormat);
    public List<Question> getQuestionsOfBodyAndOutputFormat(String body, String outputFormat);
    public List<Question> getQuestionsOfBodyAndInputTest(String body, String inputTest);
    public List<Question> getQuestionsOfBodyAndOutputTest(String body, String outputTest);
    public List<Question> getQuestionsOfBodyAndContestId(String body, String contestId);
    public List<Question> getQuestionsOfBodyAndUserId(String body, String userId);
    public List<Question> getQuestionsOfScoreAndDemoCode(String score, String demoCode);
    public List<Question> getQuestionsOfScoreAndRightPeople(String score, String rightPeople);
    public List<Question> getQuestionsOfScoreAndMainPeople(String score, String mainPeople);
    public List<Question> getQuestionsOfScoreAndStartTime(String score, String startTime);
    public List<Question> getQuestionsOfScoreAndEndTime(String score, String endTime);
    public List<Question> getQuestionsOfScoreAndInputFormat(String score, String inputFormat);
    public List<Question> getQuestionsOfScoreAndOutputFormat(String score, String outputFormat);
    public List<Question> getQuestionsOfScoreAndInputTest(String score, String inputTest);
    public List<Question> getQuestionsOfScoreAndOutputTest(String score, String outputTest);
    public List<Question> getQuestionsOfScoreAndContestId(String score, String contestId);
    public List<Question> getQuestionsOfScoreAndUserId(String score, String userId);
    public List<Question> getQuestionsOfDemoCodeAndRightPeople(String demoCode, String rightPeople);
    public List<Question> getQuestionsOfDemoCodeAndMainPeople(String demoCode, String mainPeople);
    public List<Question> getQuestionsOfDemoCodeAndStartTime(String demoCode, String startTime);
    public List<Question> getQuestionsOfDemoCodeAndEndTime(String demoCode, String endTime);
    public List<Question> getQuestionsOfDemoCodeAndInputFormat(String demoCode, String inputFormat);
    public List<Question> getQuestionsOfDemoCodeAndOutputFormat(String demoCode, String outputFormat);
    public List<Question> getQuestionsOfDemoCodeAndInputTest(String demoCode, String inputTest);
    public List<Question> getQuestionsOfDemoCodeAndOutputTest(String demoCode, String outputTest);
    public List<Question> getQuestionsOfDemoCodeAndContestId(String demoCode, String contestId);
    public List<Question> getQuestionsOfDemoCodeAndUserId(String demoCode, String userId);
    public List<Question> getQuestionsOfRightPeopleAndMainPeople(String rightPeople, String mainPeople);
    public List<Question> getQuestionsOfRightPeopleAndStartTime(String rightPeople, String startTime);
    public List<Question> getQuestionsOfRightPeopleAndEndTime(String rightPeople, String endTime);
    public List<Question> getQuestionsOfRightPeopleAndInputFormat(String rightPeople, String inputFormat);
    public List<Question> getQuestionsOfRightPeopleAndOutputFormat(String rightPeople, String outputFormat);
    public List<Question> getQuestionsOfRightPeopleAndInputTest(String rightPeople, String inputTest);
    public List<Question> getQuestionsOfRightPeopleAndOutputTest(String rightPeople, String outputTest);
    public List<Question> getQuestionsOfRightPeopleAndContestId(String rightPeople, String contestId);
    public List<Question> getQuestionsOfRightPeopleAndUserId(String rightPeople, String userId);
    public List<Question> getQuestionsOfMainPeopleAndStartTime(String mainPeople, String startTime);
    public List<Question> getQuestionsOfMainPeopleAndEndTime(String mainPeople, String endTime);
    public List<Question> getQuestionsOfMainPeopleAndInputFormat(String mainPeople, String inputFormat);
    public List<Question> getQuestionsOfMainPeopleAndOutputFormat(String mainPeople, String outputFormat);
    public List<Question> getQuestionsOfMainPeopleAndInputTest(String mainPeople, String inputTest);
    public List<Question> getQuestionsOfMainPeopleAndOutputTest(String mainPeople, String outputTest);
    public List<Question> getQuestionsOfMainPeopleAndContestId(String mainPeople, String contestId);
    public List<Question> getQuestionsOfMainPeopleAndUserId(String mainPeople, String userId);
    public List<Question> getQuestionsOfStartTimeAndEndTime(String startTime, String endTime);
    public List<Question> getQuestionsOfStartTimeAndInputFormat(String startTime, String inputFormat);
    public List<Question> getQuestionsOfStartTimeAndOutputFormat(String startTime, String outputFormat);
    public List<Question> getQuestionsOfStartTimeAndInputTest(String startTime, String inputTest);
    public List<Question> getQuestionsOfStartTimeAndOutputTest(String startTime, String outputTest);
    public List<Question> getQuestionsOfStartTimeAndContestId(String startTime, String contestId);
    public List<Question> getQuestionsOfStartTimeAndUserId(String startTime, String userId);
    public List<Question> getQuestionsOfEndTimeAndInputFormat(String endTime, String inputFormat);
    public List<Question> getQuestionsOfEndTimeAndOutputFormat(String endTime, String outputFormat);
    public List<Question> getQuestionsOfEndTimeAndInputTest(String endTime, String inputTest);
    public List<Question> getQuestionsOfEndTimeAndOutputTest(String endTime, String outputTest);
    public List<Question> getQuestionsOfEndTimeAndContestId(String endTime, String contestId);
    public List<Question> getQuestionsOfEndTimeAndUserId(String endTime, String userId);
    public List<Question> getQuestionsOfInputFormatAndOutputFormat(String inputFormat, String outputFormat);
    public List<Question> getQuestionsOfInputFormatAndInputTest(String inputFormat, String inputTest);
    public List<Question> getQuestionsOfInputFormatAndOutputTest(String inputFormat, String outputTest);
    public List<Question> getQuestionsOfInputFormatAndContestId(String inputFormat, String contestId);
    public List<Question> getQuestionsOfInputFormatAndUserId(String inputFormat, String userId);
    public List<Question> getQuestionsOfOutputFormatAndInputTest(String outputFormat, String inputTest);
    public List<Question> getQuestionsOfOutputFormatAndOutputTest(String outputFormat, String outputTest);
    public List<Question> getQuestionsOfOutputFormatAndContestId(String outputFormat, String contestId);
    public List<Question> getQuestionsOfOutputFormatAndUserId(String outputFormat, String userId);
    public List<Question> getQuestionsOfInputTestAndOutputTest(String inputTest, String outputTest);
    public List<Question> getQuestionsOfInputTestAndContestId(String inputTest, String contestId);
    public List<Question> getQuestionsOfInputTestAndUserId(String inputTest, String userId);
    public List<Question> getQuestionsOfOutputTestAndContestId(String outputTest, String contestId);
    public List<Question> getQuestionsOfOutputTestAndUserId(String outputTest, String userId);
    public List<Question> getQuestionsOfContestIdAndUserId(String contestId, String userId);
}
