package com.oj.linglian.dao;

import java.util.List;

import com.oj.linglian.entity.User;

public interface IUserDao {
    public int update(User user, User keyUser);
    public int updateOfUserId(User user, String userId);
    public int updateOfPassword(User user, String password);
    public int updateOfEmail(User user, String email);
    public int updateOfPhone(User user, String phone);
    public int updateOfSex(User user, String sex);
    public int updateOfPassQuestions(User user, String passQuestions);
    public int updateOfScore(User user, String score);
    public int updateOfLastCode(User user, String lastCode);
    public int updateOfLastQuestionId(User user, String lastQuestionId);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndEmail(User user, String userId, String email);
    public int updateOfUserIdAndPhone(User user, String userId, String phone);
    public int updateOfUserIdAndSex(User user, String userId, String sex);
    public int updateOfUserIdAndPassQuestions(User user, String userId, String passQuestions);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfUserIdAndLastCode(User user, String userId, String lastCode);
    public int updateOfUserIdAndLastQuestionId(User user, String userId, String lastQuestionId);
    public int updateOfPasswordAndEmail(User user, String password, String email);
    public int updateOfPasswordAndPhone(User user, String password, String phone);
    public int updateOfPasswordAndSex(User user, String password, String sex);
    public int updateOfPasswordAndPassQuestions(User user, String password, String passQuestions);
    public int updateOfPasswordAndScore(User user, String password, String score);
    public int updateOfPasswordAndLastCode(User user, String password, String lastCode);
    public int updateOfPasswordAndLastQuestionId(User user, String password, String lastQuestionId);
    public int updateOfEmailAndPhone(User user, String email, String phone);
    public int updateOfEmailAndSex(User user, String email, String sex);
    public int updateOfEmailAndPassQuestions(User user, String email, String passQuestions);
    public int updateOfEmailAndScore(User user, String email, String score);
    public int updateOfEmailAndLastCode(User user, String email, String lastCode);
    public int updateOfEmailAndLastQuestionId(User user, String email, String lastQuestionId);
    public int updateOfPhoneAndSex(User user, String phone, String sex);
    public int updateOfPhoneAndPassQuestions(User user, String phone, String passQuestions);
    public int updateOfPhoneAndScore(User user, String phone, String score);
    public int updateOfPhoneAndLastCode(User user, String phone, String lastCode);
    public int updateOfPhoneAndLastQuestionId(User user, String phone, String lastQuestionId);
    public int updateOfSexAndPassQuestions(User user, String sex, String passQuestions);
    public int updateOfSexAndScore(User user, String sex, String score);
    public int updateOfSexAndLastCode(User user, String sex, String lastCode);
    public int updateOfSexAndLastQuestionId(User user, String sex, String lastQuestionId);
    public int updateOfPassQuestionsAndScore(User user, String passQuestions, String score);
    public int updateOfPassQuestionsAndLastCode(User user, String passQuestions, String lastCode);
    public int updateOfPassQuestionsAndLastQuestionId(User user, String passQuestions, String lastQuestionId);
    public int updateOfScoreAndLastCode(User user, String score, String lastCode);
    public int updateOfScoreAndLastQuestionId(User user, String score, String lastQuestionId);
    public int updateOfLastCodeAndLastQuestionId(User user, String lastCode, String lastQuestionId);
    public int remove(User user);
    public int removeOfUserId(String userId);
    public int removeOfPassword(String password);
    public int removeOfEmail(String email);
    public int removeOfPhone(String phone);
    public int removeOfSex(String sex);
    public int removeOfPassQuestions(String passQuestions);
    public int removeOfScore(String score);
    public int removeOfLastCode(String lastCode);
    public int removeOfLastQuestionId(String lastQuestionId);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndEmail(String userId, String email);
    public int removeOfUserIdAndPhone(String userId, String phone);
    public int removeOfUserIdAndSex(String userId, String sex);
    public int removeOfUserIdAndPassQuestions(String userId, String passQuestions);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndLastCode(String userId, String lastCode);
    public int removeOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public int removeOfPasswordAndEmail(String password, String email);
    public int removeOfPasswordAndPhone(String password, String phone);
    public int removeOfPasswordAndSex(String password, String sex);
    public int removeOfPasswordAndPassQuestions(String password, String passQuestions);
    public int removeOfPasswordAndScore(String password, String score);
    public int removeOfPasswordAndLastCode(String password, String lastCode);
    public int removeOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public int removeOfEmailAndPhone(String email, String phone);
    public int removeOfEmailAndSex(String email, String sex);
    public int removeOfEmailAndPassQuestions(String email, String passQuestions);
    public int removeOfEmailAndScore(String email, String score);
    public int removeOfEmailAndLastCode(String email, String lastCode);
    public int removeOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public int removeOfPhoneAndSex(String phone, String sex);
    public int removeOfPhoneAndPassQuestions(String phone, String passQuestions);
    public int removeOfPhoneAndScore(String phone, String score);
    public int removeOfPhoneAndLastCode(String phone, String lastCode);
    public int removeOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public int removeOfSexAndPassQuestions(String sex, String passQuestions);
    public int removeOfSexAndScore(String sex, String score);
    public int removeOfSexAndLastCode(String sex, String lastCode);
    public int removeOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public int removeOfPassQuestionsAndScore(String passQuestions, String score);
    public int removeOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public int removeOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public int removeOfScoreAndLastCode(String score, String lastCode);
    public int removeOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public int removeOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public int insert(User user);
    public int insertOfUserId(String userId);
    public int insertOfPassword(String password);
    public int insertOfEmail(String email);
    public int insertOfPhone(String phone);
    public int insertOfSex(String sex);
    public int insertOfPassQuestions(String passQuestions);
    public int insertOfScore(String score);
    public int insertOfLastCode(String lastCode);
    public int insertOfLastQuestionId(String lastQuestionId);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndEmail(String userId, String email);
    public int insertOfUserIdAndPhone(String userId, String phone);
    public int insertOfUserIdAndSex(String userId, String sex);
    public int insertOfUserIdAndPassQuestions(String userId, String passQuestions);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndLastCode(String userId, String lastCode);
    public int insertOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public int insertOfPasswordAndEmail(String password, String email);
    public int insertOfPasswordAndPhone(String password, String phone);
    public int insertOfPasswordAndSex(String password, String sex);
    public int insertOfPasswordAndPassQuestions(String password, String passQuestions);
    public int insertOfPasswordAndScore(String password, String score);
    public int insertOfPasswordAndLastCode(String password, String lastCode);
    public int insertOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public int insertOfEmailAndPhone(String email, String phone);
    public int insertOfEmailAndSex(String email, String sex);
    public int insertOfEmailAndPassQuestions(String email, String passQuestions);
    public int insertOfEmailAndScore(String email, String score);
    public int insertOfEmailAndLastCode(String email, String lastCode);
    public int insertOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public int insertOfPhoneAndSex(String phone, String sex);
    public int insertOfPhoneAndPassQuestions(String phone, String passQuestions);
    public int insertOfPhoneAndScore(String phone, String score);
    public int insertOfPhoneAndLastCode(String phone, String lastCode);
    public int insertOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public int insertOfSexAndPassQuestions(String sex, String passQuestions);
    public int insertOfSexAndScore(String sex, String score);
    public int insertOfSexAndLastCode(String sex, String lastCode);
    public int insertOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public int insertOfPassQuestionsAndScore(String passQuestions, String score);
    public int insertOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public int insertOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public int insertOfScoreAndLastCode(String score, String lastCode);
    public int insertOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public int insertOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public User getUser(User user);
    public User getUserOfUserId(String userId);
    public User getUserOfPassword(String password);
    public User getUserOfEmail(String email);
    public User getUserOfPhone(String phone);
    public User getUserOfSex(String sex);
    public User getUserOfPassQuestions(String passQuestions);
    public User getUserOfScore(String score);
    public User getUserOfLastCode(String lastCode);
    public User getUserOfLastQuestionId(String lastQuestionId);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndEmail(String userId, String email);
    public User getUserOfUserIdAndPhone(String userId, String phone);
    public User getUserOfUserIdAndSex(String userId, String sex);
    public User getUserOfUserIdAndPassQuestions(String userId, String passQuestions);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfUserIdAndLastCode(String userId, String lastCode);
    public User getUserOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public User getUserOfPasswordAndEmail(String password, String email);
    public User getUserOfPasswordAndPhone(String password, String phone);
    public User getUserOfPasswordAndSex(String password, String sex);
    public User getUserOfPasswordAndPassQuestions(String password, String passQuestions);
    public User getUserOfPasswordAndScore(String password, String score);
    public User getUserOfPasswordAndLastCode(String password, String lastCode);
    public User getUserOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public User getUserOfEmailAndPhone(String email, String phone);
    public User getUserOfEmailAndSex(String email, String sex);
    public User getUserOfEmailAndPassQuestions(String email, String passQuestions);
    public User getUserOfEmailAndScore(String email, String score);
    public User getUserOfEmailAndLastCode(String email, String lastCode);
    public User getUserOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public User getUserOfPhoneAndSex(String phone, String sex);
    public User getUserOfPhoneAndPassQuestions(String phone, String passQuestions);
    public User getUserOfPhoneAndScore(String phone, String score);
    public User getUserOfPhoneAndLastCode(String phone, String lastCode);
    public User getUserOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public User getUserOfSexAndPassQuestions(String sex, String passQuestions);
    public User getUserOfSexAndScore(String sex, String score);
    public User getUserOfSexAndLastCode(String sex, String lastCode);
    public User getUserOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public User getUserOfPassQuestionsAndScore(String passQuestions, String score);
    public User getUserOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public User getUserOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public User getUserOfScoreAndLastCode(String score, String lastCode);
    public User getUserOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public User getUserOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public List<User> getUsers(User user);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfEmail(String email);
    public List<User> getUsersOfPhone(String phone);
    public List<User> getUsersOfSex(String sex);
    public List<User> getUsersOfPassQuestions(String passQuestions);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfLastCode(String lastCode);
    public List<User> getUsersOfLastQuestionId(String lastQuestionId);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndEmail(String userId, String email);
    public List<User> getUsersOfUserIdAndPhone(String userId, String phone);
    public List<User> getUsersOfUserIdAndSex(String userId, String sex);
    public List<User> getUsersOfUserIdAndPassQuestions(String userId, String passQuestions);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfUserIdAndLastCode(String userId, String lastCode);
    public List<User> getUsersOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public List<User> getUsersOfPasswordAndEmail(String password, String email);
    public List<User> getUsersOfPasswordAndPhone(String password, String phone);
    public List<User> getUsersOfPasswordAndSex(String password, String sex);
    public List<User> getUsersOfPasswordAndPassQuestions(String password, String passQuestions);
    public List<User> getUsersOfPasswordAndScore(String password, String score);
    public List<User> getUsersOfPasswordAndLastCode(String password, String lastCode);
    public List<User> getUsersOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public List<User> getUsersOfEmailAndPhone(String email, String phone);
    public List<User> getUsersOfEmailAndSex(String email, String sex);
    public List<User> getUsersOfEmailAndPassQuestions(String email, String passQuestions);
    public List<User> getUsersOfEmailAndScore(String email, String score);
    public List<User> getUsersOfEmailAndLastCode(String email, String lastCode);
    public List<User> getUsersOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public List<User> getUsersOfPhoneAndSex(String phone, String sex);
    public List<User> getUsersOfPhoneAndPassQuestions(String phone, String passQuestions);
    public List<User> getUsersOfPhoneAndScore(String phone, String score);
    public List<User> getUsersOfPhoneAndLastCode(String phone, String lastCode);
    public List<User> getUsersOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public List<User> getUsersOfSexAndPassQuestions(String sex, String passQuestions);
    public List<User> getUsersOfSexAndScore(String sex, String score);
    public List<User> getUsersOfSexAndLastCode(String sex, String lastCode);
    public List<User> getUsersOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public List<User> getUsersOfPassQuestionsAndScore(String passQuestions, String score);
    public List<User> getUsersOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public List<User> getUsersOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public List<User> getUsersOfScoreAndLastCode(String score, String lastCode);
    public List<User> getUsersOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public List<User> getUsersOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
}
