package com.oj.linglian.service;

import java.util.List;

import com.oj.linglian.entity.Rank;

public interface IRankService {
    public int update(Rank rank, Rank keyRank);
    public int updateOfRankId(Rank rank, String rankId);
    public int updateOfContestId(Rank rank, String contestId);
    public int updateOfUserId(Rank rank, String userId);
    public int updateOfScore(Rank rank, String score);
    public int updateOfTime(Rank rank, String time);
    public int updateOfPass(Rank rank, String pass);
    public int updateOfRankIdAndContestId(Rank rank, String rankId, String contestId);
    public int updateOfRankIdAndUserId(Rank rank, String rankId, String userId);
    public int updateOfRankIdAndScore(Rank rank, String rankId, String score);
    public int updateOfRankIdAndTime(Rank rank, String rankId, String time);
    public int updateOfRankIdAndPass(Rank rank, String rankId, String pass);
    public int updateOfContestIdAndUserId(Rank rank, String contestId, String userId);
    public int updateOfContestIdAndScore(Rank rank, String contestId, String score);
    public int updateOfContestIdAndTime(Rank rank, String contestId, String time);
    public int updateOfContestIdAndPass(Rank rank, String contestId, String pass);
    public int updateOfUserIdAndScore(Rank rank, String userId, String score);
    public int updateOfUserIdAndTime(Rank rank, String userId, String time);
    public int updateOfUserIdAndPass(Rank rank, String userId, String pass);
    public int updateOfScoreAndTime(Rank rank, String score, String time);
    public int updateOfScoreAndPass(Rank rank, String score, String pass);
    public int updateOfTimeAndPass(Rank rank, String time, String pass);
    public int remove(Rank rank);
    public int removeOfRankId(String rankId);
    public int removeOfContestId(String contestId);
    public int removeOfUserId(String userId);
    public int removeOfScore(String score);
    public int removeOfTime(String time);
    public int removeOfPass(String pass);
    public int removeOfRankIdAndContestId(String rankId, String contestId);
    public int removeOfRankIdAndUserId(String rankId, String userId);
    public int removeOfRankIdAndScore(String rankId, String score);
    public int removeOfRankIdAndTime(String rankId, String time);
    public int removeOfRankIdAndPass(String rankId, String pass);
    public int removeOfContestIdAndUserId(String contestId, String userId);
    public int removeOfContestIdAndScore(String contestId, String score);
    public int removeOfContestIdAndTime(String contestId, String time);
    public int removeOfContestIdAndPass(String contestId, String pass);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndTime(String userId, String time);
    public int removeOfUserIdAndPass(String userId, String pass);
    public int removeOfScoreAndTime(String score, String time);
    public int removeOfScoreAndPass(String score, String pass);
    public int removeOfTimeAndPass(String time, String pass);
    public int insert(Rank rank);
    public int insertOfRankId(String rankId);
    public int insertOfContestId(String contestId);
    public int insertOfUserId(String userId);
    public int insertOfScore(String score);
    public int insertOfTime(String time);
    public int insertOfPass(String pass);
    public int insertOfRankIdAndContestId(String rankId, String contestId);
    public int insertOfRankIdAndUserId(String rankId, String userId);
    public int insertOfRankIdAndScore(String rankId, String score);
    public int insertOfRankIdAndTime(String rankId, String time);
    public int insertOfRankIdAndPass(String rankId, String pass);
    public int insertOfContestIdAndUserId(String contestId, String userId);
    public int insertOfContestIdAndScore(String contestId, String score);
    public int insertOfContestIdAndTime(String contestId, String time);
    public int insertOfContestIdAndPass(String contestId, String pass);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndTime(String userId, String time);
    public int insertOfUserIdAndPass(String userId, String pass);
    public int insertOfScoreAndTime(String score, String time);
    public int insertOfScoreAndPass(String score, String pass);
    public int insertOfTimeAndPass(String time, String pass);
    public Rank getRank(Rank rank);
    public Rank getRankOfRankId(String rankId);
    public Rank getRankOfContestId(String contestId);
    public Rank getRankOfUserId(String userId);
    public Rank getRankOfScore(String score);
    public Rank getRankOfTime(String time);
    public Rank getRankOfPass(String pass);
    public Rank getRankOfRankIdAndContestId(String rankId, String contestId);
    public Rank getRankOfRankIdAndUserId(String rankId, String userId);
    public Rank getRankOfRankIdAndScore(String rankId, String score);
    public Rank getRankOfRankIdAndTime(String rankId, String time);
    public Rank getRankOfRankIdAndPass(String rankId, String pass);
    public Rank getRankOfContestIdAndUserId(String contestId, String userId);
    public Rank getRankOfContestIdAndScore(String contestId, String score);
    public Rank getRankOfContestIdAndTime(String contestId, String time);
    public Rank getRankOfContestIdAndPass(String contestId, String pass);
    public Rank getRankOfUserIdAndScore(String userId, String score);
    public Rank getRankOfUserIdAndTime(String userId, String time);
    public Rank getRankOfUserIdAndPass(String userId, String pass);
    public Rank getRankOfScoreAndTime(String score, String time);
    public Rank getRankOfScoreAndPass(String score, String pass);
    public Rank getRankOfTimeAndPass(String time, String pass);
    public List<Rank> getRanks(Rank rank);
    public List<Rank> getRanksOfRankId(String rankId);
    public List<Rank> getRanksOfContestId(String contestId);
    public List<Rank> getRanksOfUserId(String userId);
    public List<Rank> getRanksOfScore(String score);
    public List<Rank> getRanksOfTime(String time);
    public List<Rank> getRanksOfPass(String pass);
    public List<Rank> getRanksOfRankIdAndContestId(String rankId, String contestId);
    public List<Rank> getRanksOfRankIdAndUserId(String rankId, String userId);
    public List<Rank> getRanksOfRankIdAndScore(String rankId, String score);
    public List<Rank> getRanksOfRankIdAndTime(String rankId, String time);
    public List<Rank> getRanksOfRankIdAndPass(String rankId, String pass);
    public List<Rank> getRanksOfContestIdAndUserId(String contestId, String userId);
    public List<Rank> getRanksOfContestIdAndScore(String contestId, String score);
    public List<Rank> getRanksOfContestIdAndTime(String contestId, String time);
    public List<Rank> getRanksOfContestIdAndPass(String contestId, String pass);
    public List<Rank> getRanksOfUserIdAndScore(String userId, String score);
    public List<Rank> getRanksOfUserIdAndTime(String userId, String time);
    public List<Rank> getRanksOfUserIdAndPass(String userId, String pass);
    public List<Rank> getRanksOfScoreAndTime(String score, String time);
    public List<Rank> getRanksOfScoreAndPass(String score, String pass);
    public List<Rank> getRanksOfTimeAndPass(String time, String pass);
}
