package com.oj.linglian.service;

import java.util.List;

import com.oj.linglian.entity.User;

public interface IUserService {
    public int update(User user, User keyUser);
    public int updateOfUserId(User user, String userId);
    public int updateOfPassword(User user, String password);
    public int updateOfEmail(User user, String email);
    public int updateOfPhone(User user, String phone);
    public int updateOfSex(User user, String sex);
    public int updateOfPassQuestions(User user, String passQuestions);
    public int updateOfScore(User user, String score);
    public int updateOfLastCode(User user, String lastCode);
    public int updateOfLastQuestionId(User user, String lastQuestionId);
    public int updateOfLvl(User user, String lvl);
    public int updateOfParam(User user, String param);
    public int updateOfName(User user, String name);
    public int updateOfLastLogin(User user, String lastLogin);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndEmail(User user, String userId, String email);
    public int updateOfUserIdAndPhone(User user, String userId, String phone);
    public int updateOfUserIdAndSex(User user, String userId, String sex);
    public int updateOfUserIdAndPassQuestions(User user, String userId, String passQuestions);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfUserIdAndLastCode(User user, String userId, String lastCode);
    public int updateOfUserIdAndLastQuestionId(User user, String userId, String lastQuestionId);
    public int updateOfUserIdAndLvl(User user, String userId, String lvl);
    public int updateOfUserIdAndParam(User user, String userId, String param);
    public int updateOfUserIdAndName(User user, String userId, String name);
    public int updateOfUserIdAndLastLogin(User user, String userId, String lastLogin);
    public int updateOfPasswordAndEmail(User user, String password, String email);
    public int updateOfPasswordAndPhone(User user, String password, String phone);
    public int updateOfPasswordAndSex(User user, String password, String sex);
    public int updateOfPasswordAndPassQuestions(User user, String password, String passQuestions);
    public int updateOfPasswordAndScore(User user, String password, String score);
    public int updateOfPasswordAndLastCode(User user, String password, String lastCode);
    public int updateOfPasswordAndLastQuestionId(User user, String password, String lastQuestionId);
    public int updateOfPasswordAndLvl(User user, String password, String lvl);
    public int updateOfPasswordAndParam(User user, String password, String param);
    public int updateOfPasswordAndName(User user, String password, String name);
    public int updateOfPasswordAndLastLogin(User user, String password, String lastLogin);
    public int updateOfEmailAndPhone(User user, String email, String phone);
    public int updateOfEmailAndSex(User user, String email, String sex);
    public int updateOfEmailAndPassQuestions(User user, String email, String passQuestions);
    public int updateOfEmailAndScore(User user, String email, String score);
    public int updateOfEmailAndLastCode(User user, String email, String lastCode);
    public int updateOfEmailAndLastQuestionId(User user, String email, String lastQuestionId);
    public int updateOfEmailAndLvl(User user, String email, String lvl);
    public int updateOfEmailAndParam(User user, String email, String param);
    public int updateOfEmailAndName(User user, String email, String name);
    public int updateOfEmailAndLastLogin(User user, String email, String lastLogin);
    public int updateOfPhoneAndSex(User user, String phone, String sex);
    public int updateOfPhoneAndPassQuestions(User user, String phone, String passQuestions);
    public int updateOfPhoneAndScore(User user, String phone, String score);
    public int updateOfPhoneAndLastCode(User user, String phone, String lastCode);
    public int updateOfPhoneAndLastQuestionId(User user, String phone, String lastQuestionId);
    public int updateOfPhoneAndLvl(User user, String phone, String lvl);
    public int updateOfPhoneAndParam(User user, String phone, String param);
    public int updateOfPhoneAndName(User user, String phone, String name);
    public int updateOfPhoneAndLastLogin(User user, String phone, String lastLogin);
    public int updateOfSexAndPassQuestions(User user, String sex, String passQuestions);
    public int updateOfSexAndScore(User user, String sex, String score);
    public int updateOfSexAndLastCode(User user, String sex, String lastCode);
    public int updateOfSexAndLastQuestionId(User user, String sex, String lastQuestionId);
    public int updateOfSexAndLvl(User user, String sex, String lvl);
    public int updateOfSexAndParam(User user, String sex, String param);
    public int updateOfSexAndName(User user, String sex, String name);
    public int updateOfSexAndLastLogin(User user, String sex, String lastLogin);
    public int updateOfPassQuestionsAndScore(User user, String passQuestions, String score);
    public int updateOfPassQuestionsAndLastCode(User user, String passQuestions, String lastCode);
    public int updateOfPassQuestionsAndLastQuestionId(User user, String passQuestions, String lastQuestionId);
    public int updateOfPassQuestionsAndLvl(User user, String passQuestions, String lvl);
    public int updateOfPassQuestionsAndParam(User user, String passQuestions, String param);
    public int updateOfPassQuestionsAndName(User user, String passQuestions, String name);
    public int updateOfPassQuestionsAndLastLogin(User user, String passQuestions, String lastLogin);
    public int updateOfScoreAndLastCode(User user, String score, String lastCode);
    public int updateOfScoreAndLastQuestionId(User user, String score, String lastQuestionId);
    public int updateOfScoreAndLvl(User user, String score, String lvl);
    public int updateOfScoreAndParam(User user, String score, String param);
    public int updateOfScoreAndName(User user, String score, String name);
    public int updateOfScoreAndLastLogin(User user, String score, String lastLogin);
    public int updateOfLastCodeAndLastQuestionId(User user, String lastCode, String lastQuestionId);
    public int updateOfLastCodeAndLvl(User user, String lastCode, String lvl);
    public int updateOfLastCodeAndParam(User user, String lastCode, String param);
    public int updateOfLastCodeAndName(User user, String lastCode, String name);
    public int updateOfLastCodeAndLastLogin(User user, String lastCode, String lastLogin);
    public int updateOfLastQuestionIdAndLvl(User user, String lastQuestionId, String lvl);
    public int updateOfLastQuestionIdAndParam(User user, String lastQuestionId, String param);
    public int updateOfLastQuestionIdAndName(User user, String lastQuestionId, String name);
    public int updateOfLastQuestionIdAndLastLogin(User user, String lastQuestionId, String lastLogin);
    public int updateOfLvlAndParam(User user, String lvl, String param);
    public int updateOfLvlAndName(User user, String lvl, String name);
    public int updateOfLvlAndLastLogin(User user, String lvl, String lastLogin);
    public int updateOfParamAndName(User user, String param, String name);
    public int updateOfParamAndLastLogin(User user, String param, String lastLogin);
    public int updateOfNameAndLastLogin(User user, String name, String lastLogin);
    public int remove(User user);
    public int removeOfUserId(String userId);
    public int removeOfPassword(String password);
    public int removeOfEmail(String email);
    public int removeOfPhone(String phone);
    public int removeOfSex(String sex);
    public int removeOfPassQuestions(String passQuestions);
    public int removeOfScore(String score);
    public int removeOfLastCode(String lastCode);
    public int removeOfLastQuestionId(String lastQuestionId);
    public int removeOfLvl(String lvl);
    public int removeOfParam(String param);
    public int removeOfName(String name);
    public int removeOfLastLogin(String lastLogin);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndEmail(String userId, String email);
    public int removeOfUserIdAndPhone(String userId, String phone);
    public int removeOfUserIdAndSex(String userId, String sex);
    public int removeOfUserIdAndPassQuestions(String userId, String passQuestions);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndLastCode(String userId, String lastCode);
    public int removeOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public int removeOfUserIdAndLvl(String userId, String lvl);
    public int removeOfUserIdAndParam(String userId, String param);
    public int removeOfUserIdAndName(String userId, String name);
    public int removeOfUserIdAndLastLogin(String userId, String lastLogin);
    public int removeOfPasswordAndEmail(String password, String email);
    public int removeOfPasswordAndPhone(String password, String phone);
    public int removeOfPasswordAndSex(String password, String sex);
    public int removeOfPasswordAndPassQuestions(String password, String passQuestions);
    public int removeOfPasswordAndScore(String password, String score);
    public int removeOfPasswordAndLastCode(String password, String lastCode);
    public int removeOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public int removeOfPasswordAndLvl(String password, String lvl);
    public int removeOfPasswordAndParam(String password, String param);
    public int removeOfPasswordAndName(String password, String name);
    public int removeOfPasswordAndLastLogin(String password, String lastLogin);
    public int removeOfEmailAndPhone(String email, String phone);
    public int removeOfEmailAndSex(String email, String sex);
    public int removeOfEmailAndPassQuestions(String email, String passQuestions);
    public int removeOfEmailAndScore(String email, String score);
    public int removeOfEmailAndLastCode(String email, String lastCode);
    public int removeOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public int removeOfEmailAndLvl(String email, String lvl);
    public int removeOfEmailAndParam(String email, String param);
    public int removeOfEmailAndName(String email, String name);
    public int removeOfEmailAndLastLogin(String email, String lastLogin);
    public int removeOfPhoneAndSex(String phone, String sex);
    public int removeOfPhoneAndPassQuestions(String phone, String passQuestions);
    public int removeOfPhoneAndScore(String phone, String score);
    public int removeOfPhoneAndLastCode(String phone, String lastCode);
    public int removeOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public int removeOfPhoneAndLvl(String phone, String lvl);
    public int removeOfPhoneAndParam(String phone, String param);
    public int removeOfPhoneAndName(String phone, String name);
    public int removeOfPhoneAndLastLogin(String phone, String lastLogin);
    public int removeOfSexAndPassQuestions(String sex, String passQuestions);
    public int removeOfSexAndScore(String sex, String score);
    public int removeOfSexAndLastCode(String sex, String lastCode);
    public int removeOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public int removeOfSexAndLvl(String sex, String lvl);
    public int removeOfSexAndParam(String sex, String param);
    public int removeOfSexAndName(String sex, String name);
    public int removeOfSexAndLastLogin(String sex, String lastLogin);
    public int removeOfPassQuestionsAndScore(String passQuestions, String score);
    public int removeOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public int removeOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public int removeOfPassQuestionsAndLvl(String passQuestions, String lvl);
    public int removeOfPassQuestionsAndParam(String passQuestions, String param);
    public int removeOfPassQuestionsAndName(String passQuestions, String name);
    public int removeOfPassQuestionsAndLastLogin(String passQuestions, String lastLogin);
    public int removeOfScoreAndLastCode(String score, String lastCode);
    public int removeOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public int removeOfScoreAndLvl(String score, String lvl);
    public int removeOfScoreAndParam(String score, String param);
    public int removeOfScoreAndName(String score, String name);
    public int removeOfScoreAndLastLogin(String score, String lastLogin);
    public int removeOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public int removeOfLastCodeAndLvl(String lastCode, String lvl);
    public int removeOfLastCodeAndParam(String lastCode, String param);
    public int removeOfLastCodeAndName(String lastCode, String name);
    public int removeOfLastCodeAndLastLogin(String lastCode, String lastLogin);
    public int removeOfLastQuestionIdAndLvl(String lastQuestionId, String lvl);
    public int removeOfLastQuestionIdAndParam(String lastQuestionId, String param);
    public int removeOfLastQuestionIdAndName(String lastQuestionId, String name);
    public int removeOfLastQuestionIdAndLastLogin(String lastQuestionId, String lastLogin);
    public int removeOfLvlAndParam(String lvl, String param);
    public int removeOfLvlAndName(String lvl, String name);
    public int removeOfLvlAndLastLogin(String lvl, String lastLogin);
    public int removeOfParamAndName(String param, String name);
    public int removeOfParamAndLastLogin(String param, String lastLogin);
    public int removeOfNameAndLastLogin(String name, String lastLogin);
    public int insert(User user);
    public int insertOfUserId(String userId);
    public int insertOfPassword(String password);
    public int insertOfEmail(String email);
    public int insertOfPhone(String phone);
    public int insertOfSex(String sex);
    public int insertOfPassQuestions(String passQuestions);
    public int insertOfScore(String score);
    public int insertOfLastCode(String lastCode);
    public int insertOfLastQuestionId(String lastQuestionId);
    public int insertOfLvl(String lvl);
    public int insertOfParam(String param);
    public int insertOfName(String name);
    public int insertOfLastLogin(String lastLogin);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndEmail(String userId, String email);
    public int insertOfUserIdAndPhone(String userId, String phone);
    public int insertOfUserIdAndSex(String userId, String sex);
    public int insertOfUserIdAndPassQuestions(String userId, String passQuestions);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndLastCode(String userId, String lastCode);
    public int insertOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public int insertOfUserIdAndLvl(String userId, String lvl);
    public int insertOfUserIdAndParam(String userId, String param);
    public int insertOfUserIdAndName(String userId, String name);
    public int insertOfUserIdAndLastLogin(String userId, String lastLogin);
    public int insertOfPasswordAndEmail(String password, String email);
    public int insertOfPasswordAndPhone(String password, String phone);
    public int insertOfPasswordAndSex(String password, String sex);
    public int insertOfPasswordAndPassQuestions(String password, String passQuestions);
    public int insertOfPasswordAndScore(String password, String score);
    public int insertOfPasswordAndLastCode(String password, String lastCode);
    public int insertOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public int insertOfPasswordAndLvl(String password, String lvl);
    public int insertOfPasswordAndParam(String password, String param);
    public int insertOfPasswordAndName(String password, String name);
    public int insertOfPasswordAndLastLogin(String password, String lastLogin);
    public int insertOfEmailAndPhone(String email, String phone);
    public int insertOfEmailAndSex(String email, String sex);
    public int insertOfEmailAndPassQuestions(String email, String passQuestions);
    public int insertOfEmailAndScore(String email, String score);
    public int insertOfEmailAndLastCode(String email, String lastCode);
    public int insertOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public int insertOfEmailAndLvl(String email, String lvl);
    public int insertOfEmailAndParam(String email, String param);
    public int insertOfEmailAndName(String email, String name);
    public int insertOfEmailAndLastLogin(String email, String lastLogin);
    public int insertOfPhoneAndSex(String phone, String sex);
    public int insertOfPhoneAndPassQuestions(String phone, String passQuestions);
    public int insertOfPhoneAndScore(String phone, String score);
    public int insertOfPhoneAndLastCode(String phone, String lastCode);
    public int insertOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public int insertOfPhoneAndLvl(String phone, String lvl);
    public int insertOfPhoneAndParam(String phone, String param);
    public int insertOfPhoneAndName(String phone, String name);
    public int insertOfPhoneAndLastLogin(String phone, String lastLogin);
    public int insertOfSexAndPassQuestions(String sex, String passQuestions);
    public int insertOfSexAndScore(String sex, String score);
    public int insertOfSexAndLastCode(String sex, String lastCode);
    public int insertOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public int insertOfSexAndLvl(String sex, String lvl);
    public int insertOfSexAndParam(String sex, String param);
    public int insertOfSexAndName(String sex, String name);
    public int insertOfSexAndLastLogin(String sex, String lastLogin);
    public int insertOfPassQuestionsAndScore(String passQuestions, String score);
    public int insertOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public int insertOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public int insertOfPassQuestionsAndLvl(String passQuestions, String lvl);
    public int insertOfPassQuestionsAndParam(String passQuestions, String param);
    public int insertOfPassQuestionsAndName(String passQuestions, String name);
    public int insertOfPassQuestionsAndLastLogin(String passQuestions, String lastLogin);
    public int insertOfScoreAndLastCode(String score, String lastCode);
    public int insertOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public int insertOfScoreAndLvl(String score, String lvl);
    public int insertOfScoreAndParam(String score, String param);
    public int insertOfScoreAndName(String score, String name);
    public int insertOfScoreAndLastLogin(String score, String lastLogin);
    public int insertOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public int insertOfLastCodeAndLvl(String lastCode, String lvl);
    public int insertOfLastCodeAndParam(String lastCode, String param);
    public int insertOfLastCodeAndName(String lastCode, String name);
    public int insertOfLastCodeAndLastLogin(String lastCode, String lastLogin);
    public int insertOfLastQuestionIdAndLvl(String lastQuestionId, String lvl);
    public int insertOfLastQuestionIdAndParam(String lastQuestionId, String param);
    public int insertOfLastQuestionIdAndName(String lastQuestionId, String name);
    public int insertOfLastQuestionIdAndLastLogin(String lastQuestionId, String lastLogin);
    public int insertOfLvlAndParam(String lvl, String param);
    public int insertOfLvlAndName(String lvl, String name);
    public int insertOfLvlAndLastLogin(String lvl, String lastLogin);
    public int insertOfParamAndName(String param, String name);
    public int insertOfParamAndLastLogin(String param, String lastLogin);
    public int insertOfNameAndLastLogin(String name, String lastLogin);
    public User getUser(User user);
    public User getUserOfUserId(String userId);
    public User getUserOfPassword(String password);
    public User getUserOfEmail(String email);
    public User getUserOfPhone(String phone);
    public User getUserOfSex(String sex);
    public User getUserOfPassQuestions(String passQuestions);
    public User getUserOfScore(String score);
    public User getUserOfLastCode(String lastCode);
    public User getUserOfLastQuestionId(String lastQuestionId);
    public User getUserOfLvl(String lvl);
    public User getUserOfParam(String param);
    public User getUserOfName(String name);
    public User getUserOfLastLogin(String lastLogin);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndEmail(String userId, String email);
    public User getUserOfUserIdAndPhone(String userId, String phone);
    public User getUserOfUserIdAndSex(String userId, String sex);
    public User getUserOfUserIdAndPassQuestions(String userId, String passQuestions);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfUserIdAndLastCode(String userId, String lastCode);
    public User getUserOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public User getUserOfUserIdAndLvl(String userId, String lvl);
    public User getUserOfUserIdAndParam(String userId, String param);
    public User getUserOfUserIdAndName(String userId, String name);
    public User getUserOfUserIdAndLastLogin(String userId, String lastLogin);
    public User getUserOfPasswordAndEmail(String password, String email);
    public User getUserOfPasswordAndPhone(String password, String phone);
    public User getUserOfPasswordAndSex(String password, String sex);
    public User getUserOfPasswordAndPassQuestions(String password, String passQuestions);
    public User getUserOfPasswordAndScore(String password, String score);
    public User getUserOfPasswordAndLastCode(String password, String lastCode);
    public User getUserOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public User getUserOfPasswordAndLvl(String password, String lvl);
    public User getUserOfPasswordAndParam(String password, String param);
    public User getUserOfPasswordAndName(String password, String name);
    public User getUserOfPasswordAndLastLogin(String password, String lastLogin);
    public User getUserOfEmailAndPhone(String email, String phone);
    public User getUserOfEmailAndSex(String email, String sex);
    public User getUserOfEmailAndPassQuestions(String email, String passQuestions);
    public User getUserOfEmailAndScore(String email, String score);
    public User getUserOfEmailAndLastCode(String email, String lastCode);
    public User getUserOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public User getUserOfEmailAndLvl(String email, String lvl);
    public User getUserOfEmailAndParam(String email, String param);
    public User getUserOfEmailAndName(String email, String name);
    public User getUserOfEmailAndLastLogin(String email, String lastLogin);
    public User getUserOfPhoneAndSex(String phone, String sex);
    public User getUserOfPhoneAndPassQuestions(String phone, String passQuestions);
    public User getUserOfPhoneAndScore(String phone, String score);
    public User getUserOfPhoneAndLastCode(String phone, String lastCode);
    public User getUserOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public User getUserOfPhoneAndLvl(String phone, String lvl);
    public User getUserOfPhoneAndParam(String phone, String param);
    public User getUserOfPhoneAndName(String phone, String name);
    public User getUserOfPhoneAndLastLogin(String phone, String lastLogin);
    public User getUserOfSexAndPassQuestions(String sex, String passQuestions);
    public User getUserOfSexAndScore(String sex, String score);
    public User getUserOfSexAndLastCode(String sex, String lastCode);
    public User getUserOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public User getUserOfSexAndLvl(String sex, String lvl);
    public User getUserOfSexAndParam(String sex, String param);
    public User getUserOfSexAndName(String sex, String name);
    public User getUserOfSexAndLastLogin(String sex, String lastLogin);
    public User getUserOfPassQuestionsAndScore(String passQuestions, String score);
    public User getUserOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public User getUserOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public User getUserOfPassQuestionsAndLvl(String passQuestions, String lvl);
    public User getUserOfPassQuestionsAndParam(String passQuestions, String param);
    public User getUserOfPassQuestionsAndName(String passQuestions, String name);
    public User getUserOfPassQuestionsAndLastLogin(String passQuestions, String lastLogin);
    public User getUserOfScoreAndLastCode(String score, String lastCode);
    public User getUserOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public User getUserOfScoreAndLvl(String score, String lvl);
    public User getUserOfScoreAndParam(String score, String param);
    public User getUserOfScoreAndName(String score, String name);
    public User getUserOfScoreAndLastLogin(String score, String lastLogin);
    public User getUserOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public User getUserOfLastCodeAndLvl(String lastCode, String lvl);
    public User getUserOfLastCodeAndParam(String lastCode, String param);
    public User getUserOfLastCodeAndName(String lastCode, String name);
    public User getUserOfLastCodeAndLastLogin(String lastCode, String lastLogin);
    public User getUserOfLastQuestionIdAndLvl(String lastQuestionId, String lvl);
    public User getUserOfLastQuestionIdAndParam(String lastQuestionId, String param);
    public User getUserOfLastQuestionIdAndName(String lastQuestionId, String name);
    public User getUserOfLastQuestionIdAndLastLogin(String lastQuestionId, String lastLogin);
    public User getUserOfLvlAndParam(String lvl, String param);
    public User getUserOfLvlAndName(String lvl, String name);
    public User getUserOfLvlAndLastLogin(String lvl, String lastLogin);
    public User getUserOfParamAndName(String param, String name);
    public User getUserOfParamAndLastLogin(String param, String lastLogin);
    public User getUserOfNameAndLastLogin(String name, String lastLogin);
    public List<User> getUsers(User user);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfEmail(String email);
    public List<User> getUsersOfPhone(String phone);
    public List<User> getUsersOfSex(String sex);
    public List<User> getUsersOfPassQuestions(String passQuestions);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfLastCode(String lastCode);
    public List<User> getUsersOfLastQuestionId(String lastQuestionId);
    public List<User> getUsersOfLvl(String lvl);
    public List<User> getUsersOfParam(String param);
    public List<User> getUsersOfName(String name);
    public List<User> getUsersOfLastLogin(String lastLogin);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndEmail(String userId, String email);
    public List<User> getUsersOfUserIdAndPhone(String userId, String phone);
    public List<User> getUsersOfUserIdAndSex(String userId, String sex);
    public List<User> getUsersOfUserIdAndPassQuestions(String userId, String passQuestions);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfUserIdAndLastCode(String userId, String lastCode);
    public List<User> getUsersOfUserIdAndLastQuestionId(String userId, String lastQuestionId);
    public List<User> getUsersOfUserIdAndLvl(String userId, String lvl);
    public List<User> getUsersOfUserIdAndParam(String userId, String param);
    public List<User> getUsersOfUserIdAndName(String userId, String name);
    public List<User> getUsersOfUserIdAndLastLogin(String userId, String lastLogin);
    public List<User> getUsersOfPasswordAndEmail(String password, String email);
    public List<User> getUsersOfPasswordAndPhone(String password, String phone);
    public List<User> getUsersOfPasswordAndSex(String password, String sex);
    public List<User> getUsersOfPasswordAndPassQuestions(String password, String passQuestions);
    public List<User> getUsersOfPasswordAndScore(String password, String score);
    public List<User> getUsersOfPasswordAndLastCode(String password, String lastCode);
    public List<User> getUsersOfPasswordAndLastQuestionId(String password, String lastQuestionId);
    public List<User> getUsersOfPasswordAndLvl(String password, String lvl);
    public List<User> getUsersOfPasswordAndParam(String password, String param);
    public List<User> getUsersOfPasswordAndName(String password, String name);
    public List<User> getUsersOfPasswordAndLastLogin(String password, String lastLogin);
    public List<User> getUsersOfEmailAndPhone(String email, String phone);
    public List<User> getUsersOfEmailAndSex(String email, String sex);
    public List<User> getUsersOfEmailAndPassQuestions(String email, String passQuestions);
    public List<User> getUsersOfEmailAndScore(String email, String score);
    public List<User> getUsersOfEmailAndLastCode(String email, String lastCode);
    public List<User> getUsersOfEmailAndLastQuestionId(String email, String lastQuestionId);
    public List<User> getUsersOfEmailAndLvl(String email, String lvl);
    public List<User> getUsersOfEmailAndParam(String email, String param);
    public List<User> getUsersOfEmailAndName(String email, String name);
    public List<User> getUsersOfEmailAndLastLogin(String email, String lastLogin);
    public List<User> getUsersOfPhoneAndSex(String phone, String sex);
    public List<User> getUsersOfPhoneAndPassQuestions(String phone, String passQuestions);
    public List<User> getUsersOfPhoneAndScore(String phone, String score);
    public List<User> getUsersOfPhoneAndLastCode(String phone, String lastCode);
    public List<User> getUsersOfPhoneAndLastQuestionId(String phone, String lastQuestionId);
    public List<User> getUsersOfPhoneAndLvl(String phone, String lvl);
    public List<User> getUsersOfPhoneAndParam(String phone, String param);
    public List<User> getUsersOfPhoneAndName(String phone, String name);
    public List<User> getUsersOfPhoneAndLastLogin(String phone, String lastLogin);
    public List<User> getUsersOfSexAndPassQuestions(String sex, String passQuestions);
    public List<User> getUsersOfSexAndScore(String sex, String score);
    public List<User> getUsersOfSexAndLastCode(String sex, String lastCode);
    public List<User> getUsersOfSexAndLastQuestionId(String sex, String lastQuestionId);
    public List<User> getUsersOfSexAndLvl(String sex, String lvl);
    public List<User> getUsersOfSexAndParam(String sex, String param);
    public List<User> getUsersOfSexAndName(String sex, String name);
    public List<User> getUsersOfSexAndLastLogin(String sex, String lastLogin);
    public List<User> getUsersOfPassQuestionsAndScore(String passQuestions, String score);
    public List<User> getUsersOfPassQuestionsAndLastCode(String passQuestions, String lastCode);
    public List<User> getUsersOfPassQuestionsAndLastQuestionId(String passQuestions, String lastQuestionId);
    public List<User> getUsersOfPassQuestionsAndLvl(String passQuestions, String lvl);
    public List<User> getUsersOfPassQuestionsAndParam(String passQuestions, String param);
    public List<User> getUsersOfPassQuestionsAndName(String passQuestions, String name);
    public List<User> getUsersOfPassQuestionsAndLastLogin(String passQuestions, String lastLogin);
    public List<User> getUsersOfScoreAndLastCode(String score, String lastCode);
    public List<User> getUsersOfScoreAndLastQuestionId(String score, String lastQuestionId);
    public List<User> getUsersOfScoreAndLvl(String score, String lvl);
    public List<User> getUsersOfScoreAndParam(String score, String param);
    public List<User> getUsersOfScoreAndName(String score, String name);
    public List<User> getUsersOfScoreAndLastLogin(String score, String lastLogin);
    public List<User> getUsersOfLastCodeAndLastQuestionId(String lastCode, String lastQuestionId);
    public List<User> getUsersOfLastCodeAndLvl(String lastCode, String lvl);
    public List<User> getUsersOfLastCodeAndParam(String lastCode, String param);
    public List<User> getUsersOfLastCodeAndName(String lastCode, String name);
    public List<User> getUsersOfLastCodeAndLastLogin(String lastCode, String lastLogin);
    public List<User> getUsersOfLastQuestionIdAndLvl(String lastQuestionId, String lvl);
    public List<User> getUsersOfLastQuestionIdAndParam(String lastQuestionId, String param);
    public List<User> getUsersOfLastQuestionIdAndName(String lastQuestionId, String name);
    public List<User> getUsersOfLastQuestionIdAndLastLogin(String lastQuestionId, String lastLogin);
    public List<User> getUsersOfLvlAndParam(String lvl, String param);
    public List<User> getUsersOfLvlAndName(String lvl, String name);
    public List<User> getUsersOfLvlAndLastLogin(String lvl, String lastLogin);
    public List<User> getUsersOfParamAndName(String param, String name);
    public List<User> getUsersOfParamAndLastLogin(String param, String lastLogin);
    public List<User> getUsersOfNameAndLastLogin(String name, String lastLogin);
}
